### ISSUE TITLE
pip-chill aborts with failure to find `pip.get_installed_distributions()`

### ISSUE THREAD

**Issue by ebrensi** [rbanffy/pip-chill#14]
* PIP Chill version: 0.1.7
* Python version: 2.7.15
* Operating System:  Linux Mint 18.3 Cinnamon 64-bit

### Description
pip-chill aborts with the error 
```
File ".../lib/python2.7/site-packages/pip_chill/pip_chill.py", line 20, in chill
    for distribution in pip.get_installed_distributions():
AttributeError: 'module' object has no attribute 'get_installed_distributions'

```
which is apparently a new issue since pip 10.  `get_installed_distributions` is no longer available.
I found a solution here: 
https://stackoverflow.com/questions/49923671/are-there-any-function-replacement-for-pip-get-installed-distributions-in-pip?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

and it works on my fork of `pip-chill`.  I will submit it as a pull request.

**Comment by headdab** [comment]
Same problem.
