### ISSUE TITLE
django is not included in pip-chill output

### ISSUE THREAD

**Issue by fabiocaccamo** [rbanffy/pip-chill#49]
### Environment

*   PIP Chill version: `1.0.1`
*   Python version: `3.9.0`
*   Operating System: OSX

### Description

I'm using `pip-chill` on a django project to automate `requirements.txt` generation (without dependencies) and deploy, but `pip-chill` doesn't recognize `django` as top-level installed package.

### What I Did

Running `pip freeze` I can see that `Django==3.2` is installed correctly, but running `pip-chill` the django dependency is not included in the output.

**Comment by fabiocaccamo** [comment]
Sure if any maintainer give a feedback the issue become stale.

**Comment by astarrh** [comment]
I am experiencing the same issue. I'm not sure if Django is considered a dependency in one of my other packages? Even if it is, it's important that I specify the version that is installed in my requirements. 

These is my pip-chill output: 

```
babel==2.8.0
channels==3.0.4
django-livereload-server==0.3.2
django-mail-factory==0.21
django-newsletter==0.9.1
django-tinymce==2.8.0
django-webpack-loader==0.6.0
pip-chill==1.0.1
psycopg2==2.7.5
psycopg2-binary==2.7.5
pyjwt==1.7.1
pyopenssl==20.0.1
python3-openid==3.1.0
requests-oauthlib==1.0.0
service-identity==21.1.0
```

**Comment by GammaGames** [comment]
I know what packages it's happening to so a `--force-listing` option would solve my issues.

**Comment by fabiocaccamo** [comment]
@rbanffy in my case `django` is an installed package (`python -m pip install django`) but for some reason `pip-chill` doesn't list it.

**Comment by 411A** [comment]
Same problem. Unfortunately, this library does not work as I expected, don't know why this vital feature does not exist in the `pip` itself. `pip-chill` not included some packages that I manually installed, like `Pyrogram` & `Pillow`; instead, it shows me the packages that I didn't install manually like: `isoduration jsonpointer uri-template` etc.

**Comment by rbanffy** [comment]
I noticed some surprising behavior as well. I'll see what can be done besides what a --force-listing would do.

**Comment by rbanffy** [comment]
@411A Installing `jupyter` I noticed the issue you mention. From a clean environment,

``` shell
$ python3 -m venv env2
$ . env2/bin/activate
$ pip install jupyter pip-chill
Collecting jupyter
...
$ pip-chill
fqdn==1.5.1
isoduration==20.11.0
jsonpointer==2.3
jupyter==1.0.0
pip-chill==1.0.3
uri-template==1.2.0
webcolors==1.13
```

Only `jupyter` and `pip-chill` should be shown, but some of the packages you mentioned still appear. There must be something in their metadata that confuses the chill function.

**Comment by rbanffy** [comment]
Chill, bot. Still thinking about this.

**Comment by rangel3l2** [comment]
I got the same problem ith flask.

**Comment by rbanffy** [comment]
What is your original dependencies and what does pip-chill output?

**Comment by rangel3l2** [comment]
> What is your original dependencies and what does pip-chill output?

I create a venv and installed “pip install flask”, but quem I run “pip-chill > requirements.txt” flask is not inside my dependencies inside requirements.txt file.

**Comment by rbanffy** [comment]
I can´t replicate this behavior here (Python 3.11).

When I `pip install pip-chill flask` from a clean virtual environment, running `pip-chill` gives me:

```
flask==3.0.3
pip-chill==1.0.3
```

When running with `--verbose`, I get:

```
flask==3.0.3
pip-chill==1.0.3
# blinker==1.7.0 # Installed as dependency for flask
# click==8.1.7 # Installed as dependency for flask
# itsdangerous==2.2.0 # Installed as dependency for flask
# jinja2==3.1.3 # Installed as dependency for flask
# markupsafe==2.1.5 # Installed as dependency for jinja2, werkzeug
# werkzeug==3.0.2 # Installed as dependency for flask
```

Are you starting from a clean virtual environment? What do you get when you run `pip freeze`?
