### ISSUE TITLE
When listing packages with versions, add an option to output hashes too

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/pip-chill#5]
* PIP Chill version: N/A
* Python version: N/A
* Operating System: N/A

### Description

When doing a pip-chill, we output the version of the installed packages that don't depend on other packages. We should also be able to list the hashes, to have further assurance we are getting the same versions.

### What I Did

N/A

**Comment by Yogendra0Sharma** [comment]
@rbanffy : how cloud we get hash value of installed packages using PIP.
as i know we have PIP hash command to get hash value of downloaded packages. but our site-packages contains installed folder and we are not able to get hash value. please suggest some way to get hash vlaue.

**Comment by rbanffy** [comment]
It may be entirely possible we need to also change PIP so that it keeps this information alongside the rest of the downloaded package.

**Comment by Yogendra0Sharma** [comment]
@rbanffy Thanks for the response.
do we create a new issue to PIP branch for this feature?

**Comment by rbanffy** [comment]
Probably it'd be best. PIP needs to store this information somewhere in the package directory. This would, however, be insecure - if you get write access to the directory and can modify the hash file and someone pip-chills the environment, an invalid hash would be generated, enabling a corrupted package to be installed in other machines (if combined to other man-in-the-middle attacks).
