### ISSUE TITLE
Skip package definitions tied to git repos

### ISSUE THREAD

**Issue by airguru** [rbanffy/pip-chill#54]
In my `REQUIREMENTS.txt` file, one of the lines looks like this:

```
-e git+https://github.com/user/repo.git@commit_hash#egg=package_name
```

It is a package downloaded from a specific commit in a repo. `pip freeze` leaves this line intact, however `pip-chill` replaces it with:

```
package_name=dev
```

Could we perhaps have pip-chill ignore this line as well?

**Comment by julian-poidevin** [comment]
Having the same issue 🙋🏻‍♂️
