### ISSUE TITLE
does not list a manually installed package if said package is a dependency of another manually installed package

### ISSUE THREAD

**Issue by jc9108** [rbanffy/pip-chill#58]
### Environment

*   PIP Chill version: 1.0.1
*   Python version: 3.8.10
*   Operating System: Ubuntu 20.04.4 LTS on WSL

### Description

what happened: does not list a manually installed package if said package is a dependency of another manually installed package. e.g., mutagen is a dependency of r128gain. `pip install r128gain mutagen && pip-chill --no-chill` only shows r128gain. (i guess according to the project readme this is correct but it would be nice to get a list of all manually installed packages, whether they are dependencies of other manually installed packages or not)

what i expected: should also show mutagen

**Comment by GammaGames** [comment]
Duplicate of #49, still an issue :/
