### ISSUE TITLE
We should have a -H/--hash option to output hashes

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/pip-chill#6]
* PIP Chill version: N/A
* Python version: N/A
* Operating System: N/A

### Description

Pip can verify package hashes. It'd be useful to be able to output hashes of installed packages so we can download precise versions of the packages we care about.

**Comment by Yogendra0Sharma** [comment]
Can I work on this issue ? Please assign it to me. Thanks

**Comment by rbanffy** [comment]
Sorry, @Yogendra0Sharma. I closed this one because it's a dupe of #5. Feel free to play with it.
